### PR TITLE
fix markdown link

### PR DESCRIPTION
**Pull request by harlantwood**

### CODE REVIEW

**Comment by levity** [comment]
oh hey, thanks @harlantwood :)

**Comment by levity** [comment]
that makes you our first open-source contributor! :fireworks:

**Comment by edwardwest** [comment]
woo hoo!

_______________________
*Edward West*
mobile 415.225.7335
Facebook <http://www.facebook.com/edwardjwest>  Twitter
<http://www.twitter.com/edwardwest>  LinkedIn
<http://www.linkedin.com/in/edwardwest>

**Comment by harlantwood** [comment]
Awesome, it's an honor : )

**Pull request merged**
