### PR TITLE
Add event times to events in digest

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
screen shot 2015-11-11 at 5 57 49 pm

**Comment by levity** [comment]
reduce the vertical gap between time and location and we're probably good
-- maybe (mayyyybe) make the font size the same as the footer line?

**Comment by levity** [comment]
also pls confirm that we don't get a gap in the template for posts that
don't have time and location

**Comment by robbiecarlton** [comment]
Yes no gap when there's no time or location. I narrowed the vertical gap and kept the font size the same for now. Gonna merge. If we want to make more style changes, it's all in the template.

screen shot 2015-11-12 at 12 22 35 pm

**Pull request merged**
