### PR TITLE
Explicitly lower Sails after socket update

### PR DESCRIPTION
**Pull request by richchurcher**
Let's see if this helps the Redis explosion!

### CODE REVIEW

**Comment by levity** [comment]
hmm -- interesting. we got another spike 11 minutes after you merged this

**Comment by richchurcher** [comment]
Damn :(

**Comment by richchurcher** [comment]
Time to back it out and rewrite without Sails.load?

**Comment by levity** [comment]
i want to see if it happens one more time. it's close enough that it could have been stuff from the previous deploy that didn't get cleaned up

**Pull request merged**
