### PR TITLE
Fix farm filter code and updated seed data

### LINKED ISSUE #800: Farm filters broken

### PR DESCRIPTION
**Pull request by thomasgwatson**
Closes #800

### CODE REVIEW

**Comment by thomasgwatson** [comment]
If you have previous run the fake farm data generator, you'll have to wipe that data and run it again

**Review by tibetsprague — APPROVED** [review]

**Comment by tibetsprague** [comment]
@thomasgwatson ready to merge?

**Comment by thomasgwatson** [comment]
Yes, just merged dev back in. Thought I got this one in before Loren pushed to staging but now we really ought to redo the staging db :(

**Comment by thomasgwatson** [comment]
meeeer, tests passing locally but failing in circleCI. Trying to log into circleCI with my github account but it claims that hylozoic is a 404 :(

**Pull request merged**
