### PR TITLE
Notifications socket updates

### PR DESCRIPTION
**Pull request by richchurcher**
This:
 - provides for socket.io updates from the worker process
 - updates the user socket with new notifications

Let me know if there's a better way to construct the object from Bookshelf, it feels a little klunky.

### CODE REVIEW

**Comment by levity** [comment]
Does loading the `http` hook make sails try to start listening on a port? I remembered that workers already have a stripped-down sails instance (see worker.js and skiff.js), one in which I'd intentionally disabled the `http` and `sockets` hooks because it was trying to listen on the same port as the web process.

Perhaps `sails.lift` causes this but `sails.load` doesn't?

**Comment by levity** [comment]
Although if the only purpose of this code is to get sockets working, I wonder if it wouldn't be clearer to have a `getSailsSockets` method that returns `sails.sockets`.

**Comment by richchurcher** [comment]
@levity Yeah, I did think of having a sockets-only version but my thinking went along the lines of: "If we need a sails instance in the future for a worker we'll need to repeat this." Since it was just as easy to make it slightly more generic, I opted for that but don't feel strongly about it.

The `http` hook: it definitely listens, unfortunately. This author (three years ago) worked around by rewriting the pubsub hook to not depend on sockets (which depends on http): https://blog.thesparktree.com/reusing-sailsjs-waterline-models-in-background . 

Alternatively, there's actually no reason we couldn't just write raw socket.io code as far as I can see, and write to the rooms in redis. Let me know if you want me to explore that.

**Comment by levity** [comment]
if the http hook is unable to grab the port it wants, does it still stay up and allow the websocket behavior we want?

**Comment by levity** [comment]
welp, i just tested this locally and no harm came of it. i'm going to merge it myself to keep an eye on what happens in production.

**Comment by levity** [comment]
Can you try this in production and verify that it works as expected?

**Comment by richchurcher** [comment]
@levity Sure, sorry I didn't get to it sooner! I guess it doesn't throw if it can't bind the port to listen? The networking bit of the dynos docs suggests that workers can't get inbound network requests anyway, so that may be why we're getting away with it: https://devcenter.heroku.com/articles/dynos#networking

**Comment by richchurcher** [comment]
Yep, it's working on prod:

notification_frames

I guess call it done for now, think about if we have to get all custom with it later?

**Comment by levity** [comment]
Yep, sounds good!

**Pull request merged**
