### PR TITLE
change order of checks

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity this fixes the issue of communities you're not a member of not loading correctly, It looks right to me, but please double check.

**Comment by levity** [comment]
cool, want to write a test for it?

**Comment by robbiecarlton** [comment]
sure

On Tue, Jul 12, 2016 at 2:41 PM, Lawrence Wang <notifications@github.com>
wrote:

> cool, want to write a test for it?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Hylozoic/hylo-node/pull/146#issuecomment-232190557>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA2Y9M9jFiU2PcOryHa_EgwYXYSXE-onks5qVAoNgaJpZM4JK10C>
> .
>



-- 
Robbie Carlton

719.358.3482
<robbie@authenticmanprogram.com>

**Comment by robbiecarlton** [comment]
@levity - good to merge?

**Comment by levity** [comment]
:+1:

**Comment by levity** [comment]
merged this one myself since it's time-sensitive

**Pull request merged**
