### PR TITLE
fixes issue where saving settings throws an error

### PR DESCRIPTION
**Pull request by razorman8669**
https://trello.com/c/ZWvyEYuK/463-evo-cannot-change-name-from-settings-page

### CODE REVIEW

**Comment by levity** [comment]
weird. what is it when it's defined but not a string?

**Comment by razorman8669** [comment]
@levity it's an empty object:  `{ }`

**Comment by levity** [comment]
Huh. @robbiecarlton any sense of if that's a frontend bug?

**Comment by robbiecarlton** [comment]
@levity - that would make sense. I'll take a look.

**Comment by levity** [comment]
Right so if it's a frontend bug then there'd be no need for this change :) so let's hold off on merging till that's clear

**Comment by levity** [comment]
bump

**Comment by robbiecarlton** [comment]
I'll take a look at this soon.

**Pull request merged**
