### PR TITLE
add post title to push notifications

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity good?

**Comment by levity** [comment]
I don't think we should be sending notifications about your own welcome posts.

**Comment by levity** [comment]
Sending them about other people's welcome posts is also... hmm, maybe something that should have its own setting. Maybe not a big deal at the moment, and actually probably useful for early members / moderators in a community, but potentially quite noisy.

**Comment by levity** [comment]
@edwardwest what do you think?

**Comment by robbiecarlton** [comment]
Ok, it no longer sends notifications on welcome posts. Let me know if you want it to send them on other peoples welcome posts, otherwise I'll merge...

**Comment by levity** [comment]
:shipit:

**Pull request merged**
