### PR TITLE
1006 upgrade to node 20

### LINKED ISSUE #1006: Bring hylo-node to Node 20

### PR DESCRIPTION
**Pull request by thomasgwatson**
closes #1006

### CODE REVIEW

**Review by tibetsprague — COMMENTED** [review]
this looks fine, did you test the API though? pretty sure we will need to update node-oidc

**Comment by thomasgwatson** [comment]
Ahh I did not. Thats with the tokens etc? I'd have to figure out all of
that, is it something I can do with Postman or similar?

**Comment by tibetsprague** [comment]
Yes postman. I can show youOn Sep 12, 2024, at 4:36 PM, Tom Watson ***@***.***> wrote:﻿
Ahh I did not. Thats with the tokens etc? I'd have to figure out all of

that, is it something I can do with Postman or similar?



On Thu, 12 Sept 2024 at 09:43, Tibet Sprague ***@***.***>

wrote:

**Comment by thomasgwatson** [comment]
I'm assuming I need to generate a token and then have a couple of good URLs to feed into postman.

Is the process written down somewhere? I don't see it as a script in package.json ? And do you have a few urls in your postman that you can paste here for me to test?

**Comment by tibetsprague** [comment]
the process is in the APIs.md docs. but could probably be spelled out better. Here is a simple test for the server to server APIs:

First you need to setup a client in the oidc_payloads, that looks something like this: id:openteam, type: Client, payload:	{"name": "OpenTEAM", "role": "super", "email": "openteam@openteam.yoyoyo", "client_id": "openteam", "grant_types": ["client_credentials"], "client_secret": "4d1a7dc4-64d1-4df2-acbb-0940c9d28777", "redirect_uris": [], "invite_message": "You’ve been invited to join {} on Hylo<br><br>Click below to complete your registration and connect with other growers in your network.", "invite_subject": "Connect with growers in {}", "response_types": []}							

Now in postman, first setup this request to get an auth token:
POST to http://localhost:3000/noo/oauth/token
The body is of type x-www-form-encoded
grant_type = client_credentials
client_id = openteam
client_secret = 4d1a7dc4-64d1-4df2-acbb-0940c9d28777
resource = https://hylo.com
scope = api:read api:write offline_access

Then grab the resulting access_token from the response.
Now you can create a group by doing this call:
POST to http://localhost:3000/noo/graphql
Under Authorization set it to Bearer Token and copy the access token into the Token field
The body type should be raw (you can set the syntax to JSON)
Copy in:
{
    "query": "mutation ($data: GroupInput, $asUserId: ID) { createGroup(data: $data, asUserId: $asUserId) { id name slug type parentGroups { items { id } } memberships { items { id hasModeratorRole person { id } settings { sendEmail showJoinForm sendPushNotifications } } } } }",
    "variables": {
        "data": {
            "accessibility": 0,
            "name": "Group Name",
            "slug": "sluggggg",
            "visibility": 0,
            "location": "554 6th ave, San Francisco, CA 94118",
            "moderatorDescriptor": "steward", 
            "moderatorDescriptorPlural": "stewards",
            "type": "",
            "geoShape": "{\"type\":\"Polygon\",\"coordinates\":[[[-122.2873779143148,37.80965476511156],[-122.28852419926368,37.80438721836249],[-122.27324722518668,37.802895261844725],[-122.27290392239831,37.81171093139087],[-122.2873779143148,37.80965476511156]]]}",
            "groupExtensions": [
                {
                    "type": "farm-onboarding",
                    "data": {
                        "glob": 1
                    }
                }
            ]
        },
        "asUserId": 37396
    }
}

**Comment by tibetsprague** [comment]
testing the Auth Code flow is a whole other beast. 
For that one you need to setup a client that looks like:

`id: zapier, type: Client, payload: {"name": "Zapier", "role": "none", "noPKCE": true, "client_id": "zapier", "grant_types": ["authorization_code", "refresh_token"], "client_secret": "5WfCjXiJqHsx6SuubWqyRrj4DFe72X4r", "redirect_uris": ["http://localhost:4000/auth/hylo"], "response_types": ["code"]}`

And then setup an app to do the auth code flow. here is an example that should work
[React-oauth-test.zip](https://github.com/user-attachments/files/17017361/React-oauth-test.zip)

**Comment by thomasgwatson** [comment]
- Ok, so oidc_payloads is a table in the database.
- I need to insert something that looks like that data structure you shared into the table
- then I'll have the client_id and client_secret to make the token request
- then I'll have the token to make an API call (in your example, a create-group call)

And then for the second part, 
- create another client
- run that example repo
- test out the flow in that repo

Does that sound right?

**Comment by thomasgwatson** [comment]
Screenshot 2024-09-20 at 12 25 19 PM
Do I need any of these for the oidc db row?

**Comment by tibetsprague** [comment]
Yes that sounds right, and no you don’t need those On Sep 20, 2024, at 12:31 PM, Tom Watson ***@***.***> wrote:﻿
Screenshot.2024-09-20.at.12.25.19.PM.jpg (view on web)
Do I need any of these for the oidc db row?

**Comment by thomasgwatson** [comment]
Ok, so I got the first test sorted. Successfully created a group via API.

Downloaded the oauth-test repo. `npm install` and then `npm start`. No errors but it tries to open a new tab (presumably for localhost:3000) in chrome and that doesn't happen....

Oh ok, its not running on port 3000 but on 4000. Thats a little confusing, given the readme notes say 3000

**Comment by thomasgwatson** [comment]
Screenshot 2024-09-20 at 3 00 13 PM

Ok, all looks good

**Review by tibetsprague — APPROVED** [review]

**Pull request merged**
