### PR TITLE
Community checklist

### PR DESCRIPTION
**Pull request by robbiecarlton**

### CODE REVIEW

**Comment by robbiecarlton** [comment]
@levity - good to merge

**Comment by robbiecarlton** [comment]
I merged this branch in already: https://github.com/Hylozoic/hylo-node/pull/171 so it will be easier to read once that one is merged into master.

**Comment by levity** [comment]
looks like this one has conflicts now

**Comment by robbiecarlton** [comment]
fixed conflicts

**Comment by levity** [comment]
:COOL:

**Pull request merged**
